import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(
  readFileSync(resolve(__dirname, '..', 'package.json'), 'utf-8')
);

let hash = 'unknown';
try {
  hash = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
} catch {
  // not a git repo or git is not available
}

const content = `// Auto-generated by scripts/version.mjs — do not edit
export const APP_VERSION = '${pkg.version}';
export const BUILD_HASH = '${hash}';
`;

const outPath = resolve(__dirname, '..', 'src', 'environments', 'version.ts');
writeFileSync(outPath, content, 'utf-8');

console.log(`version.ts written: v${pkg.version} (${hash})`);
