import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(
  readFileSync(resolve(__dirname, '..', 'package.json'), 'utf-8')
);

let hash = process.env.COMMIT_HASH || 'unknown';
try {
  hash = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { encoding: 'utf-8' }).trim();
} catch (e) {
  if (!process.env.COMMIT_HASH) {
    console.warn(`[version.mjs] Could not read git hash: ${e.message.trim()}. Set COMMIT_HASH env var to override.`);
  }
}

const content = `// Auto-generated by scripts/version.mjs — do not edit
export const APP_VERSION = '${pkg.version}';
export const BUILD_HASH = '${hash}';
`;

const outPath = resolve(__dirname, '..', 'src', 'environments', 'version.ts');
writeFileSync(outPath, content, 'utf-8');

console.log(`version.ts written: v${pkg.version} (${hash})`);
