export enum AppRouteSegmentEnum {
  Login = 'login',
  Register = 'register',
  Profile = 'profile',
  Users = 'users',
  Admin = 'admin',
  Roles = 'roles',
  Resources = 'resources',
  Actions = 'actions',
  FeatureFlags = 'feature-flags',
  Billing = 'billing',
  BillingSettings = 'settings',
  BillingSuccess = 'success',
  BillingCancel = 'cancel',
  OAuthCallback = 'oauth/callback',
  Forbidden = 'forbidden',
  ForgotPassword = 'forgot-password',
  ResetPassword = 'reset-password',
  VerifyEmail = 'verify-email',
  ConfirmEmailChange = 'confirm-email-change',
  Any = '**'
}
