#!/usr/bin/env bash
#
# auto-patch-cves.sh — called by .github/workflows/rebuild.yml when a Trivy scan
# finds HIGH/CRITICAL CVEs in a built image.
#
# For each affected image it tries to upgrade the vulnerable Alpine OS packages,
# preferring the stable repositories and falling back to edge only if stable is
# insufficient. On success it opens/updates a patch PR; when a CVE cannot be
# resolved (e.g. the fix conflicts with pinned sibling packages) it opens/updates
# a tracking issue with the apk resolver conflict so a human has something
# actionable. Either way it exits 1 so the deploy job stays blocked.
#
# Required env: COMMIT_HASH, IMAGE_SERVER, IMAGE_CLIENT,
#               SCAN_SERVER_FAILED, SCAN_CLIENT_FAILED, GH_TOKEN
set -euo pipefail

: "${COMMIT_HASH:?}"
: "${IMAGE_SERVER:?}"
: "${IMAGE_CLIENT:?}"

declare -A DOCKERFILE=([server]="server/Dockerfile" [client]="client/Dockerfile")
declare -A IMAGE=([server]="$IMAGE_SERVER" [client]="$IMAGE_CLIENT")
declare -A FAILED=([server]="${SCAN_SERVER_FAILED:-false}" [client]="${SCAN_CLIENT_FAILED:-false}")

PATCHED=()
STUCK_REPORT=""
ANY_STUCK=false

# Emit "name|installed|fixed" for each HIGH/CRITICAL Alpine OS finding.
extract_pkgs() {
  trivy image --format json --severity HIGH,CRITICAL --quiet "$1" |
    jq -r '
      .Results[]? | select(.Type == "alpine") | .Vulnerabilities[]?
      | select(.Severity == "HIGH" or .Severity == "CRITICAL")
      | "\(.PkgName)|\(.InstalledVersion)|\(.FixedVersion // "unknown")"
    ' | sort -u
}

rebuild() {
  local svc="$1"
  if [[ "$svc" == "client" ]]; then
    docker build --no-cache -f "${DOCKERFILE[$svc]}" \
      --build-arg COMMIT_HASH="$COMMIT_HASH" -t "${IMAGE[$svc]}" .
  else
    docker build --no-cache -f "${DOCKERFILE[$svc]}" -t "${IMAGE[$svc]}" .
  fi
}

rescan_clean() {
  trivy image --severity HIGH,CRITICAL --exit-code 1 --quiet "$1"
}

# Markdown report for an image the patcher could not fix, including the apk
# resolver conflict for each still-vulnerable package.
build_report() {
  local svc="$1" image="$2" pkgs="$3" name installed fixed
  printf '### `%s` image (`%s`)\n\n' "$svc" "$image"
  printf '| Package | Installed | Fixed |\n|---|---|---|\n'
  while IFS='|' read -r name installed fixed; do
    [[ -n "$name" ]] && printf '| %s | %s | %s |\n' "$name" "$installed" "$fixed"
  done <<< "$pkgs"
  printf '\n<details><summary>apk resolver output</summary>\n\n```\n'
  while IFS='|' read -r name installed fixed; do
    [[ -n "$name" && "$fixed" != "unknown" ]] || continue
    printf '$ apk add --simulate %s=%s\n' "$name" "$fixed"
    docker run --rm --entrypoint sh "$image" -c \
      "apk update >/dev/null 2>&1; apk add --simulate ${name}=${fixed} 2>&1" || true
    printf '\n'
  done <<< "$pkgs"
  printf '```\n</details>\n\n'
}

open_or_update_issue() {
  local body="$1" title="CVE auto-patch blocked — manual intervention required"
  local existing full_body
  gh label create auto-patch-blocked --color B60205 \
    --description "Scheduled rebuild found a CVE it could not auto-patch" 2>/dev/null || true
  full_body=$(printf '%s\n\n%s\n_Generated by the scheduled rebuild for commit `%s`._\n' \
    "Trivy found HIGH/CRITICAL CVEs the auto-patcher could not resolve from the stable or edge Alpine repositories (the fix may conflict with pinned sibling packages, or only exist in an upstream base-image rebuild)." \
    "$body" "$COMMIT_HASH")
  existing=$(gh issue list --state open --label auto-patch-blocked --json number -q '.[0].number' 2>/dev/null || true)
  if [[ -n "$existing" ]]; then
    gh issue edit "$existing" --body "$full_body"
    echo "Updated tracking issue #$existing"
  else
    gh issue create --title "$title ($(date +%Y-%m-%d))" \
      --label auto-patch-blocked --body "$full_body"
  fi
}

open_or_update_pr() {
  local branch existing body
  branch="fix/auto-cve-patch-$(date +%Y-%m-%d)"
  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git checkout -b "$branch"
  git add server/Dockerfile client/Dockerfile
  git commit -m "fix(docker): patch newly detected CVEs in base image packages"
  git push --force origin "$branch"
  body=$(printf '## Summary\nScheduled rebuild detected HIGH/CRITICAL CVEs in Alpine OS packages and patched them (verified by re-scan).\n\n**Patched images:** %s\n\n## Test plan\n- [ ] Trivy scan passes on CI after merge\n- [ ] Next scheduled rebuild deploys cleanly\n' "${PATCHED[*]}")
  existing=$(gh pr list --head "$branch" --json number -q '.[0].number' 2>/dev/null || true)
  if [[ -n "$existing" ]]; then
    gh pr edit "$existing" --body "$body"
    echo "Updated patch PR #$existing"
  else
    gh pr create --title "fix(docker): patch new CVEs ($(date +%Y-%m-%d))" --body "$body"
  fi
}

for svc in server client; do
  [[ "${FAILED[$svc]}" == "true" ]] || continue

  pkgs=$(extract_pkgs "${IMAGE[$svc]}")
  names=$(echo "$pkgs" | cut -d'|' -f1 | xargs)

  if [[ -z "$names" ]]; then
    echo "$svc: no Alpine OS packages to patch — CVEs are in application dependencies"
    ANY_STUCK=true
    STUCK_REPORT+=$(printf '### `%s` image\n\nHIGH/CRITICAL findings are in application (npm) dependencies, not Alpine OS packages. These require dependency updates, not a base-image patch.\n\n' "$svc")
    continue
  fi

  fixed=false
  for channel in stable edge; do
    echo "::group::Patching $svc via $channel — $names"
    # shellcheck disable=SC2086  # $names must word-split: one arg per package
    python3 scripts/patch-dockerfile.py --channel "$channel" "${DOCKERFILE[$svc]}" $names
    rebuild "$svc"
    echo "::endgroup::"
    if rescan_clean "${IMAGE[$svc]}"; then
      echo "$svc: resolved via $channel channel"
      PATCHED+=("$svc")
      fixed=true
      break
    fi
    echo "$svc: still vulnerable after $channel channel"
  done

  if [[ "$fixed" == false ]]; then
    ANY_STUCK=true
    STUCK_REPORT+="$(build_report "$svc" "${IMAGE[$svc]}" "$pkgs")"
  fi
done

if [[ "$ANY_STUCK" == true ]]; then
  open_or_update_issue "$STUCK_REPORT"
  echo "Auto-patch could not resolve all findings — deploy blocked, tracking issue opened"
  exit 1
fi

if [[ ${#PATCHED[@]} -gt 0 ]]; then
  open_or_update_pr
  echo "Patch PR opened — deploy blocked until the PR is reviewed and merged"
  exit 1
fi

echo "Nothing to patch"
exit 0
