/**
 * Generates shared/src/generated/casl-subjects.ts from @RegisterResource decorators.
 *
 * Scans all controller files in src/modules/ (excluding 'feature'), extracts
 * the `subject` field from each @RegisterResource decorator, and writes a
 * TypeScript union type that the client and server import as `KnownSubjects`.
 *
 * Run whenever a new resource is registered:
 *   npm run generate:subjects   (from server/)
 *
 * The generated file is committed to the repository.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as ts from 'typescript';

// ─── config ──────────────────────────────────────────────────────────────────

const CONTROLLERS_ROOT = path.resolve(__dirname, '../src/modules');
const OUTPUT_FILE = path.resolve(
  __dirname,
  '../../shared/src/generated/casl-subjects.ts'
);

/** Controller subdirectories to skip entirely. */
const EXCLUDE_DIRS = new Set(['feature']);

// ─── AST helpers ─────────────────────────────────────────────────────────────

function decoratorName(d: ts.Decorator): string | undefined {
  const expr = d.expression;
  if (ts.isCallExpression(expr) && ts.isIdentifier(expr.expression)) {
    return expr.expression.text;
  }
  return ts.isIdentifier(expr) ? expr.text : undefined;
}

function decoratorArgs(
  d: ts.Decorator
): ts.NodeArray<ts.Expression> | undefined {
  return ts.isCallExpression(d.expression) ? d.expression.arguments : undefined;
}

function stringLiteral(node: ts.Expression): string | undefined {
  return ts.isStringLiteral(node) ? node.text : undefined;
}

function parseRegisterResource(d: ts.Decorator): string | undefined {
  const args = decoratorArgs(d);
  if (!args?.length) return undefined;

  const arg = args[0];
  if (!ts.isObjectLiteralExpression(arg)) return undefined;

  for (const prop of arg.properties) {
    if (!ts.isPropertyAssignment(prop) || !ts.isIdentifier(prop.name)) continue;
    if (prop.name.text === 'subject') return stringLiteral(prop.initializer);
  }

  return undefined;
}

// ─── file scanning ────────────────────────────────────────────────────────────

function findControllers(dir: string): string[] {
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!EXCLUDE_DIRS.has(entry.name)) {
        results.push(...findControllers(path.join(dir, entry.name)));
      }
    } else if (entry.name.endsWith('.controller.ts')) {
      results.push(path.join(dir, entry.name));
    }
  }
  return results;
}

function extractSubjects(filePath: string): string[] {
  const source = fs.readFileSync(filePath, 'utf-8');
  const sf = ts.createSourceFile(
    filePath,
    source,
    ts.ScriptTarget.Latest,
    /* setParentNodes */ true
  );

  const subjects: string[] = [];

  ts.forEachChild(sf, (node) => {
    if (!ts.isClassDeclaration(node)) return;

    const classDecorators = ts.getDecorators(node);
    if (!classDecorators) return;

    for (const d of classDecorators) {
      if (decoratorName(d) === 'RegisterResource') {
        const subject = parseRegisterResource(d);
        if (subject) subjects.push(subject);
      }
    }
  });

  return subjects;
}

// ─── codegen ─────────────────────────────────────────────────────────────────

function buildFileContent(subjects: string[]): string {
  const sorted = [...new Set(subjects)].sort();
  const union = sorted.map((s) => `  | '${s}'`).join('\n');

  return [
    '// AUTO-GENERATED by server/scripts/generate-subjects.ts — do not edit manually.',
    '// Re-run: npm run generate:subjects (from server/) when adding a new @RegisterResource.',
    '',
    '// prettier-ignore',
    `export type KnownSubjects =\n${union};`,
    '',
  ].join('\n');
}

// ─── main ─────────────────────────────────────────────────────────────────────

function main(): void {
  const controllerFiles = findControllers(CONTROLLERS_ROOT);
  const allSubjects: string[] = [];

  for (const file of controllerFiles) {
    allSubjects.push(...extractSubjects(file));
  }

  if (allSubjects.length === 0) {
    console.error('✗ generate:subjects: no @RegisterResource decorators found');
    process.exit(1);
  }

  const content = buildFileContent(allSubjects);

  const outDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');

  const sorted = [...new Set(allSubjects)].sort();
  console.log(
    `✓ generate:subjects: wrote ${sorted.length} subjects to ${path.relative(process.cwd(), OUTPUT_FILE)}`
  );
  console.log(`  Subjects: ${sorted.join(', ')}`);
}

main();
